"""Entry point for OpenClaw plugin hooks: rclm-openclaw-hooks <HookName>.

OpenClaw loads the small TypeScript plugin generated by rclm-hooks-install and
that plugin forwards selected lifecycle events to this Python handler on stdin.
Hook failures must never disrupt OpenClaw, so this process always exits 0.
"""

from __future__ import annotations

import asyncio
import json
import logging
import sys
from typing import Any

from rclm._models import HookSessionRecord
from rclm._uploader import close_session, upload_single
from rclm.hooks import session_store
from rclm.hooks.openclaw_transcript import (
    as_dict,
    bounded,
    build_messages,
    build_tool_calls,
    cwd_from_payload,
    duration_s,
    first_cwd_from_events,
    first_model_from_events,
    message_from_llm_output,
    messages_from_llm_input,
    model_from_payload,
    session_id_from_payload,
    started_at_from_events,
    timestamp_from_payload,
    tool_id_from_event,
    tool_input_from_event,
    tool_name_from_event,
    tool_result_from_event,
)

logger = logging.getLogger(__name__)


def _handle_session_start(session_id: str, payload: dict) -> None:
    event = as_dict(payload.get("event"))
    session_store.append_event(
        session_id,
        {
            "event_type": "SessionStart",
            "cwd": cwd_from_payload(payload),
            "timestamp": timestamp_from_payload(payload),
            "model": model_from_payload(payload),
            "raw": bounded(event),
        },
    )


def _handle_append_event(session_id: str, payload: dict, hook_name: str) -> None:
    event = as_dict(payload.get("event"))
    timestamp = timestamp_from_payload(payload)
    stored: dict[str, Any] = {
        "event_type": hook_name,
        "timestamp": timestamp,
        "cwd": cwd_from_payload(payload),
        "model": model_from_payload(payload),
    }
    if hook_name == "llm_input":
        stored["messages"] = messages_from_llm_input(event, timestamp)
    elif hook_name == "llm_output":
        message = message_from_llm_output(event, timestamp)
        if message:
            stored["messages"] = [message]
    elif hook_name in {"before_tool_call", "after_tool_call"}:
        stored.update(
            {
                "tool_use_id": tool_id_from_event(event, 0),
                "tool_name": tool_name_from_event(event),
                "tool_input": tool_input_from_event(event),
            }
        )
        if hook_name == "after_tool_call":
            stored["tool_result"] = tool_result_from_event(event)

    stored["raw"] = bounded(event)
    session_store.append_event(session_id, stored)


async def _upload_and_close(record: HookSessionRecord, *, max_retries: int) -> None:
    """upload_single, then close the module-level aiohttp session before this
    asyncio.run() call's event loop is torn down -- see claude_handler's
    identical helper for why (aiohttp session/loop binding)."""
    try:
        await upload_single(record, max_retries=max_retries)
    finally:
        await close_session()


def _handle_session_end(session_id: str, payload: dict) -> None:
    now = timestamp_from_payload(payload)
    events = session_store.read_events(session_id)
    started_at = started_at_from_events(events, now)
    ended_at = now

    record = HookSessionRecord(
        session_id=session_id,
        cwd=first_cwd_from_events(events, cwd_from_payload(payload)),
        started_at=started_at,
        ended_at=ended_at,
        duration_s=duration_s(started_at, ended_at),
        transcript_path=None,
        model=first_model_from_events(events, model_from_payload(payload)),
        messages=build_messages(events),
        tool_calls=build_tool_calls(events),
        file_diffs=[],
        total_input_tokens=None,
        total_output_tokens=None,
    )

    asyncio.run(_upload_and_close(record, max_retries=1))
    session_store.cleanup(session_id)


_ACCUMULATE_EVENTS = {
    "llm_input",
    "llm_output",
    "before_tool_call",
    "after_tool_call",
    "agent_end",
    "message_received",
    "message_sent",
}


def _dispatch(hook_name: str, payload: dict) -> None:
    session_id = session_id_from_payload(payload)
    if hook_name == "session_start":
        _handle_session_start(session_id, payload)
    elif hook_name == "session_end":
        _handle_session_end(session_id, payload)
    elif hook_name in _ACCUMULATE_EVENTS:
        _handle_append_event(session_id, payload, hook_name)


def main() -> None:
    hook_name = sys.argv[1] if len(sys.argv) > 1 else ""
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        logger.warning("rclm-openclaw-hooks: could not parse stdin JSON for hook %s", hook_name)
        sys.exit(0)

    try:
        _dispatch(hook_name or str(payload.get("hook_name", "")), payload)
    except Exception:
        logger.exception("rclm-openclaw-hooks: unhandled error in hook %s", hook_name)

    sys.exit(0)
