"""Entry point for rclm-proxy.

Subcommands:
  rclm-proxy setup        — write ~/.reclaimllm/litellm_config.yaml interactively
  rclm-proxy start        — launch LiteLLM proxy with that config (default)
  rclm-proxy <anything>   — passed through to the litellm CLI directly
"""

from __future__ import annotations

import getpass
import os
import shutil
import subprocess
import sys
from pathlib import Path

from rclm import _config

_CONFIG_DIR = Path.home() / ".reclaimllm"
_LITELLM_CONFIG = _CONFIG_DIR / "litellm_config.yaml"
_TEMPLATE = Path(__file__).parent / "config_template.yaml"


def _require_litellm() -> None:
    if shutil.which("litellm") is None:
        print(
            "error: litellm not found.\nInstall the proxy extra with:\n  pip install 'rclm[proxy]'",
            file=sys.stderr,
        )
        sys.exit(1)


def cmd_setup() -> None:
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    cfg = _config.load()

    # Server URL
    current_url = os.environ.get("RECLAIMLLM_SERVER_URL") or cfg.get("server_url", "")
    url_hint = f" [{current_url}]" if current_url else ""
    server_url = input(f"ReclaimLLM server URL{url_hint}: ").strip() or current_url

    # API key
    current_key = os.environ.get("RECLAIMLLM_API_KEY") or cfg.get("api_key", "")
    key_hint = " [********]" if current_key else ""
    api_key = getpass.getpass(f"ReclaimLLM API key{key_hint}: ").strip() or current_key

    if server_url and api_key:
        _config.save(server_url, api_key)
        print("  Saved credentials → ~/.reclaimllm/config.json")

    _LITELLM_CONFIG.write_text(_TEMPLATE.read_text())
    print(f"  Wrote proxy config → {_LITELLM_CONFIG}")
    print()
    print("Set your provider API keys as environment variables before starting:")
    print("  export ANTHROPIC_API_KEY=sk-ant-...")
    print("  export OPENAI_API_KEY=sk-...")
    print("  export GEMINI_API_KEY=...")
    print()
    print("Then start the proxy:")
    print("  rclm-proxy start")


def _ensure_callback_shim() -> None:
    """LiteLLM resolves callbacks as file paths relative to the config directory.
    Write a shim there that re-exports from the installed package."""
    shim_path = _CONFIG_DIR / "rclm" / "proxy" / "litellm_callback.py"
    shim_path.parent.mkdir(parents=True, exist_ok=True)
    shim_path.write_text(
        "# Auto-generated by rclm-proxy — do not edit.\n"
        "from rclm.proxy.litellm_callback import proxy_handler_instance  # noqa: F401\n"
    )


def cmd_start(extra_args: list[str]) -> None:
    _require_litellm()

    if not _LITELLM_CONFIG.exists():
        print(
            f"error: no proxy config found at {_LITELLM_CONFIG}\nRun 'rclm-proxy setup' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    _ensure_callback_shim()

    cmd = ["litellm", "--config", str(_LITELLM_CONFIG), *extra_args]
    print(f"Starting ReclaimLLM proxy via LiteLLM  (config: {_LITELLM_CONFIG})")
    subprocess.run(cmd, env=os.environ.copy())


def main() -> None:
    args = sys.argv[1:]

    if not args or args[0] == "start":
        cmd_start(args[1:] if args else [])
    elif args[0] == "setup":
        cmd_setup()
    else:
        # Unknown subcommand — pass straight through to litellm CLI
        _require_litellm()
        subprocess.run(["litellm", *args], env=os.environ.copy())


if __name__ == "__main__":
    main()
